name: umeng_analytics_plugin
description: A Umeng analytics Flutter plugin.
version: 1.0.0
author: Ji Tao <jitao@jitao.tech>
homepage: https://github.com/flmn/umeng_analytics_plugin

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: tech.jitao.umeng_analytics_plugin
    pluginClass: UmengAnalyticsPlugin
